In [54]:
import pandas as pd
vehicles = pd.read_excel("data/route_map.xlsx",sheet_name=0)

In [55]:
vehicles

,SLNL,Vehicle,Camera,TimeStamp,GPS location,reID
0,1,red car,Dharmashala Junction,2022-05-25 09:55:45,"11.98638, 75.37624",1
1,2,red car,Dharmashala Canara Bank,2022-05-25 09:56:21,"11.98702, 75.38011",1
2,3,red car,ID road,2022-05-25 09:56:37,"11.98811, 75.38138",1
3,4,red car,Parassini Snake Park,2022-05-25 09:57:41,"11.99012, 75.38865",1
4,5,red car,Vismaya Park,2022-05-25 09:59:01,"11.99179, 75.39458",1
5,6,red car,Parassini Bridge1,2022-05-25 10:01:06,"11.98811, 75.38138",1
6,7,red car,Parassini Bridge 2,2022-05-25 10:01:26,"11.98811, 75.38138",1
7,8,black bike,MiZone,2022-05-25 09:31:28,"11.98811, 75.38138",2
8,9,black bike,Dharmashala Junction,2022-05-25 09:32:58,"11.98638, 75.37624",2
9,10,black bike,GCEK back entrance,2022-05-25 09:33:46,"11.98702, 75.38011",2
10,11,black auto,Vismaya Park,2022-05-25 10:03:38,"11.99179, 75.39458",3
11,12,black auto,Parassini Snake Park,2022-05-25 10:04:43,"11.99012, 75.38865",3
12,13,black auto,ID road,2022-05-25 10:05:54,"11.98811, 75.38138",3
13,14,black auto,Dharmashala Canara Bank,2022-05-25 10:06:07,"11.98702, 75.38011",3
14,15,black auto,NIFT,2022-05-25 10:06:18,"11.98811, 75.38138",3
15,16,white tempo traveller,Parassini Snake Park,2022-05-25 09:45:18,"11.99012, 75.38865",4
16,17,white tempo traveller,ID road,2022-05-25 09:46:45,"11.98811, 75.38138",4
17,18,white tempo traveller,Dharmashala Canara Bank,2022-05-25 09:46:56,"11.98702, 75.38011",4
18,19,white tempo traveller,GCEK back entrance,2022-05-25 09:47:38,"11.98702, 75.38011",4
19,20,blue car,NIFT,2022-05-25 10:15:15,"11.98811, 75.38138",5
20,21,blue car,Dharmashala Canara Bank,2022-05-25 10:15:38,"11.98702, 75.38011",5
21,22,blue car,Dharmashala Junction,2022-05-25 10:16:09,"11.98638, 75.37624",5

In [56]:
vehicles['color'] = vehicles.apply(lambda row: row['Vehicle'].split()[0], axis=1)
vehicles['Vehicle'] = vehicles.apply(lambda row: " ".join(row['Vehicle'].split()[1:]), axis=1)

In [57]:
vehicles

,SLNL,Vehicle,Camera,TimeStamp,GPS location,reID,color
0,1,car,Dharmashala Junction,2022-05-25 09:55:45,"11.98638, 75.37624",1,red
1,2,car,Dharmashala Canara Bank,2022-05-25 09:56:21,"11.98702, 75.38011",1,red
2,3,car,ID road,2022-05-25 09:56:37,"11.98811, 75.38138",1,red
3,4,car,Parassini Snake Park,2022-05-25 09:57:41,"11.99012, 75.38865",1,red
4,5,car,Vismaya Park,2022-05-25 09:59:01,"11.99179, 75.39458",1,red
5,6,car,Parassini Bridge1,2022-05-25 10:01:06,"11.98811, 75.38138",1,red
6,7,car,Parassini Bridge 2,2022-05-25 10:01:26,"11.98811, 75.38138",1,red
7,8,bike,MiZone,2022-05-25 09:31:28,"11.98811, 75.38138",2,black
8,9,bike,Dharmashala Junction,2022-05-25 09:32:58,"11.98638, 75.37624",2,black
9,10,bike,GCEK back entrance,2022-05-25 09:33:46,"11.98702, 75.38011",2,black
10,11,auto,Vismaya Park,2022-05-25 10:03:38,"11.99179, 75.39458",3,black
11,12,auto,Parassini Snake Park,2022-05-25 10:04:43,"11.99012, 75.38865",3,black
12,13,auto,ID road,2022-05-25 10:05:54,"11.98811, 75.38138",3,black
13,14,auto,Dharmashala Canara Bank,2022-05-25 10:06:07,"11.98702, 75.38011",3,black
14,15,auto,NIFT,2022-05-25 10:06:18,"11.98811, 75.38138",3,black
15,16,tempo traveller,Parassini Snake Park,2022-05-25 09:45:18,"11.99012, 75.38865",4,white
16,17,tempo traveller,ID road,2022-05-25 09:46:45,"11.98811, 75.38138",4,white
17,18,tempo traveller,Dharmashala Canara Bank,2022-05-25 09:46:56,"11.98702, 75.38011",4,white
18,19,tempo traveller,GCEK back entrance,2022-05-25 09:47:38,"11.98702, 75.38011",4,white
19,20,car,NIFT,2022-05-25 10:15:15,"11.98811, 75.38138",5,blue
20,21,car,Dharmashala Canara Bank,2022-05-25 10:15:38,"11.98702, 75.38011",5,blue
21,22,car,Dharmashala Junction,2022-05-25 10:16:09,"11.98638, 75.37624",5,blue

In [58]:
prune = vehicles[vehicles['Vehicle']=='car']
prune = prune[prune['color']=='red']
prune = prune.sort_values('TimeStamp')

In [59]:
prune

,SLNL,Vehicle,Camera,TimeStamp,GPS location,reID,color
0,1,car,Dharmashala Junction,2022-05-25 09:55:45,"11.98638, 75.37624",1,red
1,2,car,Dharmashala Canara Bank,2022-05-25 09:56:21,"11.98702, 75.38011",1,red
2,3,car,ID road,2022-05-25 09:56:37,"11.98811, 75.38138",1,red
3,4,car,Parassini Snake Park,2022-05-25 09:57:41,"11.99012, 75.38865",1,red
4,5,car,Vismaya Park,2022-05-25 09:59:01,"11.99179, 75.39458",1,red
5,6,car,Parassini Bridge1,2022-05-25 10:01:06,"11.98811, 75.38138",1,red
6,7,car,Parassini Bridge 2,2022-05-25 10:01:26,"11.98811, 75.38138",1,red

In [60]:
for index,row in prune.iterrows():
    print(row['Camera'],row['TimeStamp'])

Dharmashala Junction 2022-05-25 09:55:45
Dharmashala Canara Bank 2022-05-25 09:56:21
ID road 2022-05-25 09:56:37
Parassini Snake Park 2022-05-25 09:57:41
Vismaya Park 2022-05-25 09:59:01
Parassini Bridge1 2022-05-25 10:01:06
Parassini Bridge 2 2022-05-25 10:01:26

In [71]:
import pandas as pd
def get_route(vehicle,color,**kwarg):
    vehicles = pd.read_excel("data/route_map.xlsx",sheet_name=0)
    
    vehicles['color'] = vehicles.apply(lambda row: row['Vehicle'].split()[0], axis=1)
    vehicles['Vehicle'] = vehicles.apply(lambda row: " ".join(row['Vehicle'].split()[1:]), axis=1)
    vehicles['GPS location'] = vehicles.apply(lambda row: "".join(row['GPS location'].split()), axis=1)
    
    prune = vehicles[vehicles['Vehicle']==vehicle]
    prune = prune[prune['color']==color]
    prune = prune.sort_values('TimeStamp')
    
    result = list()
    for index,row in prune.iterrows():
        result.append((row['Camera'],str(row['TimeStamp']),row['GPS location']))
    return result

get_route('car','red')

In [74]:
get_route('car','red')

[('Dharmashala Junction', '2022-05-25 09:55:45', '11.98638,75.37624'),
 ('Dharmashala Canara Bank', '2022-05-25 09:56:21', '11.98702,75.38011'),
 ('ID road', '2022-05-25 09:56:37', '11.98811,75.38138'),
 ('Parassini Snake Park', '2022-05-25 09:57:41', '11.99012,75.38865'),
 ('Vismaya Park', '2022-05-25 09:59:01', '11.99179,75.39458'),
 ('Parassini Bridge1', '2022-05-25 10:01:06', '11.98811,75.38138'),
 ('Parassini Bridge 2', '2022-05-25 10:01:26', '11.98811,75.38138')]